In [2]:
%matplotlib inline
import torch
import numpy as np

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

print('Using gpu: %s ' % torch.cuda.is_available())

Using gpu: True 


# Autograd: automatic differentiation

![backprop1](https://dataflowr.github.io/notebooks/Module2/img/backprop1.png)

In [16]:
w = np.array([0.5])
x = np.array([0.5])
b = np.array([2.0])

In [17]:
w_t = torch.from_numpy(w)
b_t = torch.from_numpy(b)
x_t = torch.from_numpy(x)

In [20]:
w_t.requires_grad_(True)
b_t.requires_grad_(True)

tensor([2.], dtype=torch.float64, requires_grad=True)

In [34]:
def forward(x, y_star):
    y = torch.exp(w_t*x + b_t)
    return torch.sum((y-y_star)**2)

In [35]:
y_star = torch.rand_like(x_t)
l_t = forward(x_t, y_star)

In [36]:
l_t.requires_grad

True

In [37]:
l_t.backward()

In [38]:
w_t.grad.data.zero_()
b_t.grad.data.zero_()
l_t = forward(x_t, y_star)
l_t.backward(retain_graph=True)
print(w_t.grad)
print(b_t.grad)

tensor([80.5858], dtype=torch.float64)
tensor([161.1716], dtype=torch.float64)
